version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodejs
    overwrite: true
hooks:
  BeforeInstall:
    - location: BeforeInstallHook.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: AfterInstallHook.sh
      timeout: 300
      runas: ubuntu